FROM oven/bun:1

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./apps/backend .

RUN bun install
RUN cd ./packages/db && bun install
# RUN cd ./packages/db && bunx prisma generate --debug

EXPOSE 8080

CMD ["sh", "-c", "echo STARTING && cd packages/db && ls && bunx prisma generate && cd ../.. && ls && bun run index.ts && pws && ls"]

